# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44d3bb84527b780c40b8aac14d1a9f897656746fc4072b99941bc1e11b8fc3a91d9477e89c300e21e215180645bff87cd5b599da707c8e241bca3196075cf652

test:
  secret_key_base: 24aa8a664b1d60f7e41152166f22d0c5fb32e3eda7912cf5940a9f628969dfaf4c7c7f5716f8bbce3fde6f60ecd19d4489c335cfea1b0b47caaf5c31359d8c59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
